all:
	@$(MAKE) --no-print-directory -f makefile.4bit clean all
	@$(MAKE) --no-print-directory -f makefile.8bit clean all
	@$(MAKE) --no-print-directory -f makefile.15bit clean all
	@$(MAKE) --no-print-directory -f makefile.24bit clean all

clean:
	@$(MAKE) --no-print-directory -f makefile.4bit clean
	@$(MAKE) --no-print-directory -f makefile.8bit clean
	@$(MAKE) --no-print-directory -f makefile.15bit clean
	@$(MAKE) --no-print-directory -f makefile.24bit clean

# I know, I know... This can be written in much better way