all:
	@$(MAKE) --no-print-directory -f makefile.15bit clean all
	@$(MAKE) --no-print-directory -f makefile.24bit clean all

clean:
	@$(MAKE) --no-print-directory -f makefile.15bit clean
	@$(MAKE) --no-print-directory -f makefile.24bit clean
