all:
	@$(MAKE) --no-print-directory -f makefile.15bit     clean all
	@$(MAKE) --no-print-directory -f makefile.15bit-dma clean all
	@$(MAKE) --no-print-directory -f makefile.24bit     clean all
	@$(MAKE) --no-print-directory -f makefile.24bit-dma clean all

clean:
	@$(MAKE) --no-print-directory -f makefile.15bit clean
